import argparse
import api
import sys
import pathlib

def _main(argv):
    parser = argparse.ArgumentParser(description='BACnet DecentFS cli', epilog='Version: ' + api.DecentFs.VERSION)
    parser.add_argument('--keyfile', help='A key generated by crypto.py', type=pathlib.Path)
    parser.add_argument('--storage', help='Use an existing DecentFS path', type=pathlib.Path)
    parser.add_argument('--opt', help='Pass custom options', type=ascii)

    args = parser.parse_args()

    if args.keyfile is None:
        print("No keyfile specified", file=sys.stderr)
        parser.print_help()
        sys.exit(1)

    if args.opt is None:
        opt = ''
    else:
        opt = args.opt

    if args.storage is None:
        try:
            myDecentFs = api.DecentFs(args.keyfile, opt=opt)
        except FileExistsError:
            print('File or Directory already exists', file=sys.stderr)
            sys.exit(1)
    else:
        myDecentFs = api.DecentFs(args.keyfile, args.storage, opt=opt)

if __name__ == '__main__':
    _main(sys.argv[1:])
